/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administracionprospectos;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author José Carlos Jiménez
 */
public class VentanaListado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaListado
     */
    DefaultTableModel modelo;
    String id, nombre, apellidoP, apellidoM, status;
    public VentanaListado() {
        initComponents();
        objetosInvisibles();
        String[] titulo = {"id", "Nombre", "Apellido Paterno", "Apellido Materno", "status"};
        modelo = new DefaultTableModel(null,titulo);
        tblProspectos.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProspectos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        lb10 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellidoP = new javax.swing.JLabel();
        lbApellidoM = new javax.swing.JLabel();
        lbCalle = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        lbColonia = new javax.swing.JLabel();
        lbCodigoPostal = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbRfc = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        lbObservaciones = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProspectos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tblProspectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProspectos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblProspectos.setSelectionBackground(new java.awt.Color(222, 222, 222));
        tblProspectos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblProspectos.setShowVerticalLines(false);
        tblProspectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProspectosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProspectos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 493, 162));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Listado de Prospectos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        btnVer.setBackground(new java.awt.Color(10, 81, 175));
        btnVer.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnVer.setForeground(new java.awt.Color(255, 255, 255));
        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        btnVolver.setBackground(new java.awt.Color(10, 81, 175));
        btnVolver.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        lb1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb1.setText("Nombre");
        getContentPane().add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        lb2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb2.setText("Apellido Paterno:");
        getContentPane().add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        lb3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb3.setText("Apellido Materno:");
        getContentPane().add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        lb4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb4.setText("Calle:");
        getContentPane().add(lb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        lb5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb5.setText("Numero:");
        getContentPane().add(lb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        lb6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb6.setText("Colonia:");
        getContentPane().add(lb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        lb7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb7.setText("Codigo Postal:");
        getContentPane().add(lb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        lb8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb8.setText("Teléfono:");
        getContentPane().add(lb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        lb9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb9.setText("RFC:");
        getContentPane().add(lb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        lb10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb10.setText("Status");
        getContentPane().add(lb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        lb11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb11.setText("Observaciones:");
        getContentPane().add(lb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        lbNombre.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbNombre.setText("x");
        getContentPane().add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        lbApellidoP.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbApellidoP.setText("x");
        getContentPane().add(lbApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        lbApellidoM.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbApellidoM.setText("x");
        getContentPane().add(lbApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        lbCalle.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbCalle.setText("x");
        getContentPane().add(lbCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        lbNumero.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbNumero.setText("x");
        getContentPane().add(lbNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        lbColonia.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbColonia.setText("x");
        getContentPane().add(lbColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        lbCodigoPostal.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbCodigoPostal.setText("x");
        getContentPane().add(lbCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        lbTelefono.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbTelefono.setText("x");
        getContentPane().add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        lbRfc.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbRfc.setText("x");
        getContentPane().add(lbRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        lbStatus.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbStatus.setText("x");
        getContentPane().add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        lbObservaciones.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbObservaciones.setText("x");
        getContentPane().add(lbObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jPanel1.setBackground(new java.awt.Color(10, 81, 175));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Prospectos");

        btnSalir1.setBackground(new java.awt.Color(255, 22, 22));
        btnSalir1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("X");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 226, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(136, 136, 136)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSalir1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.hide();
        Ventana v =new Ventana();
        v.setLocationRelativeTo(null);
        v.show();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tblProspectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProspectosMouseClicked
        //preguntamos si se dio un click, en caso de que si, el lector guardara el id del prospecto
        if(evt.getClickCount() == 1){
            JTable lector = (JTable) evt.getSource();
            
            //el lector guarda el id del prospecto en la variable id
            id = lector.getModel().getValueAt(lector.getSelectedRow(),0).toString();
            nombre = lector.getModel().getValueAt(lector.getSelectedRow(),1).toString();
            apellidoP = lector.getModel().getValueAt(lector.getSelectedRow(),2).toString();
            apellidoM = lector.getModel().getValueAt(lector.getSelectedRow(),3).toString();
            status = lector.getModel().getValueAt(lector.getSelectedRow(),4).toString();
            //System.out.println(id);
        }
    }//GEN-LAST:event_tblProspectosMouseClicked

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        //mostramos los datos del prospecto seleccionado   
        verDatos();
        objetosInvisibles();
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void objetosInvisibles(){
        if(lbNombre.isVisible()==true && lbNombre.getText()=="x"){
            
            lb1.setVisible(false);
            lb2.setVisible(false);
            lb3.setVisible(false);
            lb4.setVisible(false);
            lb5.setVisible(false);
            lb6.setVisible(false);
            lb7.setVisible(false);
            lb8.setVisible(false);
            lb9.setVisible(false);
            lb10.setVisible(false);
            lb11.setVisible(false);
            lbNombre.setVisible(false);
            lbApellidoP.setVisible(false);
            lbApellidoM.setVisible(false);
            lbCalle.setVisible(false);
            lbNumero.setVisible(false);
            lbColonia.setVisible(false);
            lbCodigoPostal.setVisible(false);
            lbTelefono.setVisible(false);
            lbRfc.setVisible(false);
            lbStatus.setVisible(false);
            lbObservaciones.setVisible(false);
        }
        else{
            lb1.setVisible(true);
            lb2.setVisible(true);
            lb3.setVisible(true);
            lb4.setVisible(true);
            lb5.setVisible(true);
            lb6.setVisible(true);
            lb7.setVisible(true);
            lb8.setVisible(true);
            lb9.setVisible(true);
            lb10.setVisible(true);
            lb11.setVisible(true);
            lbNombre.setVisible(true);
            lbApellidoP.setVisible(true);
            lbApellidoM.setVisible(true);
            lbCalle.setVisible(true);
            lbNumero.setVisible(true);
            lbColonia.setVisible(true);
            lbCodigoPostal.setVisible(true);
            lbTelefono.setVisible(true);
            lbRfc.setVisible(true);
            lbStatus.setVisible(true);
            lbObservaciones.setVisible(true);
        }
    }
    public void mostarDatos(){
        DBConexion dbc = new DBConexion();
        
        try {
            ResultSet resultado = dbc.consultarDatos("SELECT "
                    + "id, nombre, apellidoPaterno, apellidoMaterno, status "
                    + "FROM tblprospectos;");
            
            while(resultado.next()){
                Object[] obj = {
                    resultado.getString("id"),
                    resultado.getString("nombre"),
                    resultado.getString("apellidoPaterno"),
                    resultado.getString("apellidoMaterno"),
                    resultado.getString("status")};
                modelo.addRow(obj);
            }
        } catch (Exception e) {
            System.out.println(e);
        }        
    }
    
    public void verDatos(){
        DBConexion dbc = new DBConexion();
        try {
            ResultSet resultado = dbc.consultarDatos("SELECT * FROM tblprospectos WHERE "
                    + "id ='"+id+ "'"
                    + "OR nombre ='"+nombre+"'"
                    + "OR apellidoPaterno ='"+apellidoP+"'"
                    + "OR apellidoMaterno ='"+apellidoM+"'"
                    + "OR status ='"+status+"';");
            
            resultado.next();
            lbNombre.setText(resultado.getString("nombre"));
            lbApellidoP.setText(resultado.getString("apellidoPaterno"));
            lbApellidoM.setText(resultado.getString("apellidoMaterno"));
            lbCalle.setText(resultado.getString("calle"));
            lbNumero.setText(resultado.getString("numero"));
            lbColonia.setText(resultado.getString("colonia"));
            lbCodigoPostal.setText(resultado.getString("codigoPostal"));
            lbTelefono.setText(resultado.getString("telefono"));
            lbRfc.setText(resultado.getString("rfc"));
            lbStatus.setText(resultado.getString("status"));
            lbObservaciones.setText(resultado.getString("observaciones"));
            
            
        } catch (SQLException e) {
            System.out.println(e);
        }   
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaListado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir1;
    public javax.swing.JButton btnVer;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JLabel lbApellidoM;
    private javax.swing.JLabel lbApellidoP;
    private javax.swing.JLabel lbCalle;
    private javax.swing.JLabel lbCodigoPostal;
    private javax.swing.JLabel lbColonia;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbObservaciones;
    private javax.swing.JLabel lbRfc;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JTable tblProspectos;
    // End of variables declaration//GEN-END:variables
}
